# Generated by Django 4.1.3 on 2022-11-10 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "new"),
                            ("in progress", "in progress"),
                            ("resolved", "resolved"),
                        ],
                        default="new",
                        max_length=50,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("web", "website platform"),
                            ("line", "LINE platform"),
                            ("mobile", "mobile app platform"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="media/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "mp4"]
                            )
                        ],
                    ),
                ),
                ("department", models.ManyToManyField(to="help_support.department")),
            ],
        ),
    ]
