# Generated by Django 4.1.3 on 2022-11-10 12:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_support", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="software_version",
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="issue",
            name="file",
            field=models.FileField(
                upload_to="customer_uploads/",
                validators=[
                    django.core.validators.FileExtensionValidator(["png", "jpg", "mp4"])
                ],
            ),
        ),
    ]
