# Generated by Django 4.1.3 on 2022-11-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_support", "0002_issue_software_version_alter_issue_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="software_version",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
